encrypted_private_key = 'Awj5oZjsJkX4GByNVfyU/yGfS121TxXhsDVf77052TtciRN+H+VejaYDMOvOZSBDuHGBlNX8Da8='
num_signers = 2
public_keys = ['f0462dff74ca3e4a2e8b6d5fb80c1b1da3fc578ceb8bec03bb2cc2d99d8b5201']
